apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: techprocess
data:
  SPRING_PROFILES_ACTIVE: docker
  KEYCLOAK_TOKEN_URI: "http://keycloak:8080/realms/techprocess-service-realm/protocol/openid-connect/token"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "http://keycloak:8080/realms/techprocess-service-realm"
  KEYCLOAK_CLIENT_ID: api-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: techprocess
spec:
  selector:
    app: api-gateway
  ports:
    - port: 8083
      targetPort: 8083
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: techprocess
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: n1ruin/api-gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: api-gateway-config
          env:
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-gateway-secret
                  key: client-secret
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 15