apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: techprocess
  labels:
    app: vault
spec:
  selector:
    app: vault
  ports:
    - name: http
      port: 8200
      targetPort: 8200
      protocol: TCP
    - name: cluster
      port: 8201
      targetPort: 8201
      protocol: TCP
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: vault-ui
  namespace: techprocess
  labels:
    app: vault
spec:
  selector:
    app: vault
  ports:
    - name: http
      port: 8200
      targetPort: 8200
      protocol: TCP
  type: ClusterIP